### ISSUE TITLE
Inconsistent behaviour of API making tests a bit fragile

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/fabric8-analytics-jobs#87] opened 2017-06-27 10:04 UTC
The following simple test shows that one API call (analyses-report) causes internal error even if API itself seems to be ok (from the outside):

```
def readiness():
    response = requests.get("http://localhost:34000/api/v1/readiness")
    print(response.url)
    print(response.status_code)

def analyses_report(ecosystem):
    response = requests.get("http://localhost:34000/api/v1/debug/analyses-report?ecosystem=" + ecosystem)
    print(response.url)
    print(response.status_code)

while True:
    try:
        readiness()
        analyses_report("maven")
        print("")
    except:
        print("can not connect")
    time.sleep(5)
```

When the system is being started, the following inconsistent state can be seen *sometimes*:

```
http://localhost:34000/api/v1/readiness
200
http://localhost:34000/api/v1/debug/analyses-report?ecosystem=maven
500
```

the next iteration (five seconds later) is ok on my (quite fast) machine:

```
http://localhost:34000/api/v1/readiness
200
http://localhost:34000/api/v1/debug/analyses-report?ecosystem=maven
200
```

then everything is ok, but the intermediate state is not good :/

See #82

**Comment by tisnik** [comment] 2017-06-27 10:16
This might be the error that caused the 500 internal error:

```
coreapi-jobs            | [2017-06-27 09:58:44,748] ERROR in app: Exception on /api/v1/debug/analyses-report [GET]
coreapi-jobs            | Traceback (most recent call last):
coreapi-jobs            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
coreapi-jobs            |     context)
coreapi-jobs            |   File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
coreapi-jobs            |     cursor.execute(statement, parameters)
coreapi-jobs            | psycopg2.ProgrammingError: relation "worker_results" does not exist
coreapi-jobs            | LINE 3: FROM worker_results JOIN analyses ON analyses.id = worker_re...
coreapi-jobs            |              ^
coreapi-jobs            |
```

**Comment by fridex** [comment] 2017-06-27 10:56
Spoke to @tisnik privately - a summary:

This issue is caused by not ready database as database migrations are in progress - readiness probe does not rely on the database to be ready (another component in the system), but stack-analysis is querying database which is at that time not ready.

This shouldn't happen in production as our database migrations are backwards compatible so there is no strong service version vs database version interconnection (backwards compatible with one version back).

Closing this as this is not an issue.

**Closed by fridex** 2017-06-27 10:56 UTC
